### ISSUE TITLE
ModuleNotFoundError when trying to import slicerio.server

### ISSUE THREAD

**Issue by AtlasCodex** [lassoan/slicerio#11]
Hello,

I'm encountering an issue while trying to use the `slicerio` library in my Python environment. When I attempt to import the `server` module from `slicerio`, I receive a `ModuleNotFoundError`. Here's the error message I'm getting:
  

I've confirmed that I have the `slicerio` library installed, and I'm using the latest version. Here are the steps I've taken to try and resolve the issue:

1. I've ensured that my Python environment is clean and up-to-date.
2. I've reinstalled the `slicerio` library using `pip install --upgrade slicerio`.
3. I've checked the official documentation and GitHub repository for any updates or changes to the library structure.

However, I'm still unable to import the `server` module. I believe this might be a recent change in the library or there might be a missing component in the installation.

Here's a minimal example of the code that's causing the issue:

```python
import slicerio.server
```

**Comment by lassoan** [comment]
I could not reproduce this behavior. Everything looks good to me.

For example:

```
PS C:\D\sliceriotest> pip install --upgrade slicerio                                                                                                                                                               
Requirement already satisfied: slicerio in c:\d\sliceriotest\.venv\lib\site-packages (1.1.1)
Requirement already satisfied: pynrrd in c:\d\sliceriotest\.venv\lib\site-packages (from slicerio) (1.0.0)
Requirement already satisfied: numpy in c:\d\sliceriotest\.venv\lib\site-packages (from slicerio) (1.26.4)
Requirement already satisfied: requests in c:\d\sliceriotest\.venv\lib\site-packages (from slicerio) (2.32.3)
Requirement already satisfied: nptyping in c:\d\sliceriotest\.venv\lib\site-packages (from pynrrd->slicerio) (2.5.0)
Requirement already satisfied: typing-extensions in c:\d\sliceriotest\.venv\lib\site-packages (from pynrrd->slicerio) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\d\sliceriotest\.venv\lib\site-packages (from requests->slicerio) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\d\sliceriotest\.venv\lib\site-packages (from requests->slicerio) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\d\sliceriotest\.venv\lib\site-packages (from requests->slicerio) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\d\sliceriotest\.venv\lib\site-packages (from requests->slicerio) (2024.8.30)
PS C:\D\sliceriotest> python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import slicerio.server
>>> server = slicerio.server.start_server(r"c:\users\andra\AppData\Local\slicer.org\Slicer 5.7.0-2024-07-14\Slicer.exe")
>>> 
```

I've also downloaded the [latest wheel](https://files.pythonhosted.org/packages/b6/39/6e19df9a05113371a831c653ef2136441a18520e8b6f0e68a740dc1fe155/slicerio-1.1.1-py3-none-any.whl), unzipped it, and it contains the server module (slicerio-1.1.1-py3-none-any.whl\slicerio\server.py).

---

What is your Python version? What version of slicerio did you install?

**Comment by AtlasCodex** [comment]
Thank you for your response. I've made some progress, but I've encountered a new issue. When running the script in my editor, I get the following error:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\demo\slicerUtil.py", line 2, in <module>
    server = slicerio.server.start_server(r"D:\Slicer 5.6.2\Slicer.exe")
AttributeError: module 'slicerio' has no attribute 'server'

However, when I try the same command in the Python console, it works without any issues. I'm using Python version 3.9.19, and the version of slicerio I have installed is 1.1.0.

Could you please help me understand why this might be happening and how I can resolve it?

Thank you!

![局部截取_20240910_163048](https://github.com/user-attachments/assets/87f4cfdf-d1c5-439a-8dcd-b192c8661a3e)
![局部截取_20240910_163102](https://github.com/user-attachments/assets/7486a8c4-d02f-4d61-ba10-cf77608b3a17)

**Comment by lassoan** [comment]
`import slicerio` is not sufficient if you want to use `slicerio.server`. This works:

```
import slicerio.server
server = slicerio.server.start_server(r"c:\users\andra\AppData\Local\slicer.org\Slicer 5.7.0-2024-07-14\Slicer.exe")
```

**Comment by AtlasCodex** [comment]
Thank you very much for your assistance with the issue. Your explanation was extremely helpful and has clarified things for me.

Great job on the support and for providing such a detailed resolution. It's much appreciated! 👍
